### PR TITLE
WIXBUG:4791 - Fix race in lit.exe/light.exe related to wixlibs and large binaries.

### PR DESCRIPTION
**Pull request by jmcooper8654**
Modifications to CompareFiles() and LayoutMedia() to avoid races when building MultiProc on TFS 2013.  As a side benefit, the switch to using P/INVOKE memcmp() in part shaved a 50 minute build down to 17-19 minutes.

Builds are all for WCF services and have multiple duplicated assemblies (for client support) in each AppPool.  Large ZIP modules (up to 26 megs compressed) are also built and added to the MSI's.

### CODE REVIEW

**Comment by barnson** [comment]
158 commits is...a lot. :) Can you try `git pull --rebase` to rebase your changes on top of the head of develop branch? Right now, I can't even see yours...

**Comment by jmcooper8654** [comment]
Sure.  158 is a lot more than I expected.  Should be only three files involved.  I tried to pare it down to the minimum.

--

John M. Cooper

**Comment by jmcooper8654** [comment]
Affected files should ONLY be

 

History/4791.md

History.md

Src/tools/wix/BinderFileManager.cs

Src/tools/wix/WixBinder.cs

 

Don’t know how I managed to fat finger this.  I may have inadvertently based off of Master, but I’m not sure.

 

Anyway, I executed git pull –rebase after cleaning up the “added” files.

 

Should be good now.

--

John M. Cooper

**Comment by barnson** [comment]
Can you push to your fork's branch? That should update the pull request.

**Comment by jmcooper8654** [comment]
Yes, but it will to wait for the morning.  I’ll do it first thing.  That computer is at work.

 

--

John M. Cooper

Leavenworth, KS

**Comment by jmcooper8654** [comment]
I’m presuming a:

 

git push origin HEAD

 

from wix3-jmc-pr local is what is desired.

 

--

John M. Cooper

Leavenworth, KS

**Comment by jmcooper8654** [comment]
Changes have been pushed.

--
John Merryweather Cooper
Senior Software Engineer | Integration Development Group | Enterprise Notification Service
Jack Henry & Associates, Inc.® | Lenexa, KS  66214 | Ext:  431050 |JoCooper@jackhenry.com<mailto:JoCooper@jackhenry.com>



From: John Merryweather Cooper [mailto:j.m.cooper@borgsdemons.com]
Sent: Sunday, June 21, 2015 4:27 PM
To: 'wixtoolset/wix3'
Cc: John Cooper
Subject: RE: [wix3] WIXBUG:4791 - Fix race in lit.exe/light.exe related to wixlibs and large binaries. (#271)

The e-mail below is from an external source.  Please do not open attachments or click links from an unknown or suspicious origin.
Yes, but it will to wait for the morning.  I’ll do it first thing.  That computer is at work.

--
John M. Cooper
Leavenworth, KS

**Comment by barnson** [comment]
No go. Try this:

git pull --rebase https://github.com/wixtoolset/wix3.git develop

That will get the latest changes from the wix3 repo into your fork. Then push again.

**Comment by jmcooper8654** [comment]
Bummer.  I brought my company laptop just so I could RDP in.  It will be done shortly.

 

--

John M. Cooper

Leavenworth, KS

**Comment by jmcooper8654** [comment]
Ok, that command line gives me:

 

Cannot pull with rebase:  You have unstaged changes.

Please commit or stash them.

 

Probably the heart of the matter.

 

--

John M. Cooper

Leavenworth, KS

**Comment by jmcooper8654** [comment]
Ok, that wasn’t it.  It was just an .gitignore file which I just did a git checkout -- .gitignore to remove.

 

Then reran the command and it almost succeeded.  Got some other files pending that I don’t care for.  Working on that.

 

--

John M. Cooper

Leavenworth, KS

**Comment by jmcooper8654** [comment]
Ok, there was a merge resolve conflict in history.md

 

I ran git rebase –skip to skip past it.  Hope this works.

 

--

John M. Cooper

Leavenworth, KS

**Comment by barnson** [comment]
Did you push? I don't see any other commits...

**Comment by jmcooper8654** [comment]
Yes, I pushed last night.  If this continues to be an issue, hit me on my work address (JoCooper@jackhenry.com) so I can get on this immediately.

 

--

John M. Cooper

Leavenworth, KS

**Comment by jmcooper8654** [comment]
Ok, my changes appear to have gotten removed.  Re-doing the commits and pushing up.

**Comment by jmcooper8654** [comment]
The commits look like they are there this morning.

**Comment by barnson** [comment]
It's not showing up here. I took a look at your fork at https://github.com/jmcooper8654/wix3 and it's not showing any of the changes in the wix3 repo since April. ("This branch is 1 commit ahead, 129 commits behind wixtoolset:develop") Are you sure the push was successful?

**Comment by jmcooper8654** [comment]
No, just that is was without error.  When I click on the Pull Request link, I can see the diffs for the files.

 

Looks like I’ll have to try, try again.

 

--

John M. Cooper

Leavenworth, KS

**Comment by jmcooper8654** [comment]
Hmmm.  Looked in my fork at jmcooper8654\wix and the changes are definitely there.  I'll redo the pull request as there's clearly something wrong with it.

**Comment by jmcooper8654** [comment]
This PR is erroneous and is being closed.  A successor has already been created.

**Pull request closed without merging**
