### PR TITLE
WIXBUG:4662 - WIX_IS_NETFRAMEWORK_4XX_OR_LATER_INSTALLED

### PR DESCRIPTION
**Pull request by barnson**
Add WIX_IS_NETFRAMEWORK_4XX_OR_LATER_INSTALLED SetProperty custom
actions to WixNetfxExtension.

### CODE REVIEW

**Comment by bc3tech** [comment]
I'm running Wix 3.9 and when I try to use this property I get:
error LGHT0094: Unresolved reference to symbol 'Property:WIX_IS_NETFRAMEWORK_451_OR_LATER_INSTALLED' in section 'Product:*'.

**Comment by robmen** [comment]
New to WiX v3.10.

**Comment by bc3tech** [comment]
Can we get that put on the doco page like the other variables "as of WiX 3.5" etc?

**Comment by barnson** [comment]
@bc3tech Please open an issue so we don't lose it.

**Comment by bc3tech** [comment]
@barnson sure thing... Though i'm a bit confused as to what you would like to see different than what's in this one?

**Pull request merged**
