### PR TITLE
Fix app.config name translation for projects with no exe output

### PR DESCRIPTION
**Pull request by apmorton**
http://wixtoolset.org/issues/4335/

### CODE REVIEW

**Comment by rseanhall** [comment]
We've moved to the .NET Foundation, but we're having trouble getting the bot to check older pull requests.  Here's what it would normally say:

Hi @apmorton, I'm your friendly neighborhood .NET Foundation Pull Request Bot (You can call me DNFBOT). Thanks for your contribution!

In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla2.dotnetfoundation.org.

TTYL, DNFBOT;

**Comment by apmorton** [comment]
@rseanhall done

**Comment by rseanhall** [comment]
Thanks!

**Comment by apmorton** [comment]
wow, that was a whole year ago? time really flies!

Thanks for pulling.

**Pull request closed without merging**
