### PR TITLE
WIXBUG:4882 - handle all kinds of bad version strings in WixTagExtension

### PR DESCRIPTION
**Pull request by firegiantco**
Should have added these the first time around.

### CODE REVIEW

**Comment by rseanhall** [comment]
Can FireGiant port these SWID tag pull requests to v4?

**Comment by barnson** [comment]
If you're sure you can give up the fun of cherry-picking! :)

**Comment by rseanhall** [comment]
I think you misunderstand, I want to spread around the joy of cherry picking! :)

**Comment by barnson** [comment]
https://www.youtube.com/watch?v=NmPhaG1ud38

**Pull request merged**
