### PR TITLE
Allow lit binder extensions to parse command line arguments

### PR DESCRIPTION
**Pull request by heaths**
Resolves issue https://github.com/wixtoolset/issues/issues/4894.

### CODE REVIEW

**Comment by heaths** [comment]
@barnson, could we get a 3.11 branch so we can target changes and get this in the next build? Or keep develop going and branch for 3.10.3 (probably easier to manage that way)?

**Comment by barnson** [comment]
`develop` is v3.11.

**Comment by barnson** [comment]
Build failure because no .wixlibs aren't built:

    95>Target "Lib" in file "Y:\wixbuild\ship\x86\wix2010.targets" from project "Z:\src\wix3\src\ext\DependencyExtension\wixlib\DependencyExtension.wixproj" (target "CompileAndLink" depends on it):
       Building target "Lib" completely.
       Output file "Y:\wixbuild\ship\x86\dependency.wixlib" does not exist.
       Using "Lit" task from assembly "Y:\wixbuild\ship\x86\WixTasks.dll".
       Task "Lit"
         Command:
         Y:\wixbuild\ship\x86\lit.exe -sw1086 -wx -out Y:\wixbuild\ship\x86\dependency.wixlib -b Y:\wixbuild\ship\x86\ -b x86=Y:\wixbuild\ship\x86\ -b x64=Y:\wixbuild\ship\x64\ -b arm=Y:\wixbuild\ship\arm\ -bf -loc en-us.wxl -loc Z:\src\wix3\src\common\WixDistribution.wxl -pedantic Y:\wixbuild\obj\ship\x86\DependencyExtension\DependencyExtension.wixobj Y:\wixbuild\obj\ship\x86\DependencyExtension\DependencyExtension_x86.wixobj
...
    95>Lib:
         Windows Installer XML Toolset Library Tool version 3.11.0.226
         Copyright (c) Outercurve Foundation. All rights reserved.
         
          usage:  lit.exe [-?] [-nologo] [-out libraryFile] objectFile [objectFile ...] [@responseFile]
         
            -b <path>  binder path to locate all files (default: current directory)
                       prefix the path with 'name=' where 'name' is the name of your
                       named bindpath.
            -bf        bind files into the library file
            -ext <extension>  extension assembly or "class, assembly"
            -loc <loc.wxl>  bind localization strings from a wxl into the library file
            -nologo    skip printing lit logo information
            -o[ut]     specify output file (default: write to current directory)
            -pedantic  show pedantic messages
            -ss        suppress schema validation of documents (performance boost)
            -sv        suppress intermediate file version mismatch checking
            -sw[N]     suppress all warnings or a specific message ID
                       (example: -sw1011 -sw1012)
            -swall     suppress all warnings (deprecated)
            -v         verbose output
            -wx[N]     treat all warnings or a specific message ID as an error
                       (example: -wx1011 -wx1012)
            -wxall     treat all warnings as errors (deprecated)
            -? | -help this help information
         
         For more information see: http://wixtoolset.org/
       Done executing task "Lit".

**Comment by heaths** [comment]
Was that doing a full build of wix? Apart from the problem building the chm (again), I was able to build every other MSI without error.

**Comment by heaths** [comment]
Never mind. I was able to reproduce it. I must not have cleaned a previous build like I had thought. Looking into it now.

**Comment by heaths** [comment]
Transposition error from the diff of our internal wix37 sources. Fixed and amended the commit for such a small diff. Forced pushed back to this PR.

**Comment by heaths** [comment]
No need for a port to wix4 as this is already supported therein.

**Pull request closed without merging**
