### PR TITLE
Add StrAllocConcatFormatted to concatenate a formatted string to an e…

### PR DESCRIPTION
**Pull request by barnson**
…xisting string.

### CODE REVIEW

**Comment by heaths** [comment]
Why was this necessary? You can actually use `StrAllocFormated` for that - I did in several places. The implementation actually supports this by, IIRC, swapping if necessary.

**Comment by barnson** [comment]
@heaths, this is when you have one string and want to concatenate a new formatted string to it. The typical StrUtil reuse doesn't get concatenation.

**Comment by heaths** [comment]
The following works. Use it in a few places.

``` c++
StrAllocString(&wz, L"name: ", 0);
StrAllocFormatted(&wz, L"%ls %hs", wz, "Bob");
```

I supposed it's not intuitive, though. IIRC, can't do that with normal "printf" routines in the CRT.

Code is fine.

**Comment by barnson** [comment]
True. It's a bit voodoo to refer to the variable you're updating...like it's something that works in C# but shouldn't work in C++ because C++ always makes you pay...

**Comment by heaths** [comment]
LGTM

**Pull request closed without merging**
