### PR TITLE
Added italian translation

### PR DESCRIPTION
**Pull request by piccoloaiutante**
Added the italian translation to the UtilExtension project. This PR is part of a larger effort to create an italian installer for NodeJS.

### CODE REVIEW

**Comment by piccoloaiutante** [comment]
Thanks @barnson for the approval. Is this code going to be a part of the weekly release?

**Comment by barnson** [comment]
Yes, it will be part of the next WiX v3.11 build.

**Comment by piccoloaiutante** [comment]
@barnson Do you have any timeframe for v3.11 release?

**Comment by barnson** [comment]
Not before the next version of Visual Studio.

**Comment by piccoloaiutante** [comment]
Would it be possible to have a weekly release like the one the you did on 7th of June?

**Comment by rseanhall** [comment]
This in the [3.11.0705 weekly release](http://wixtoolset.org/releases/v3-11-0-705/).

**Comment by piccoloaiutante** [comment]
Thanks @rseanhall

**Pull request merged**
